on: [push]

jobs:
  label-czar:
    runs-on: ubuntu-latest
    name: Validate the labels
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate the label
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          target: 'release-2.0'
      # Use the output from the `hello` step
      - name: Get the result
        run: echo "The result is ${{ steps.hello.outputs.results }}"