name: 'Label Validator'
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  label-czar:
    runs-on: ubuntu-latest
    name: Validate the labels
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate the label
        uses: david-bour/nalc@v1.0
        with:
          expectedLabels: 'release*'